# Generated by Django 5.2.4 on 2025-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('Onboarding', 'Onboarding'), ('Newsletter', 'Newsletter'), ('Promotional', 'Promotional'), ('Transactional', 'Transactional'), ('Reminder', 'Reminder'), ('Announcement', 'Announcement')], max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
