# Generated by Django 5.2.4 on 2025-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0003_alter_group_mobile_number_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='mobile_number',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
