# Generated by Django 5.2.4 on 2025-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0005_messagestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestatus',
            old_name='channel',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='messagestatus',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='recipient',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
