# Generated by Django 5.2 on 2025-08-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0006_rename_channel_messagestatus_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageStatus',
        ),
    ]
