# Generated by Django 5.2.4 on 2025-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_management', '0006_rename_channel_messagestatus_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageStatus',
        ),
        migrations.RemoveField(
            model_name='group',
            name='company',
        ),
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('business', 'Business'), ('member', 'Member'), ('staff', 'Staff'), ('all', 'All')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='group',
            name='mobile_number',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
