# Generated by Django 5.2 on 2025-06-17 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_common', '0021_tempbusinessuser_is_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicInformation', models.JSONField(default=dict)),
                ('CareerObjectivesPreferences', models.JSONField(default=dict)),
                ('EducationDetails', models.JSONField(default=dict)),
                ('WorkExperience', models.JSONField(default=dict)),
                ('SkillsCompetencies', models.JSONField(default=dict)),
                ('AchievementsExtracurricular', models.JSONField(default=dict)),
                ('OtherDetails', models.JSONField(default=dict)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('MbrCardNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='JobProfile', to='app_common.member', to_field='mbrcardno')),
            ],
        ),
    ]
