# Generated by Django 5.2 on 2025-05-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofilefield',
            name='category',
        ),
        migrations.DeleteModel(
            name='FieldCategory',
        ),
        migrations.DeleteModel(
            name='JobProfileField',
        ),
    ]
