# Generated by Django 5.2 on 2025-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_fieldcategory_jobprofilefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofilefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('url', 'URL'), ('textarea', 'Textarea')], max_length=20),
        ),
    ]
