# Generated by Django 5.2 on 2025-08-25 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_jobprofilefield_field_type'),
        ('app_common', '0031_alter_business_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentInstituteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('government_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_institutes', to='app_common.governmentuser')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_governments', to='app_common.business')),
            ],
        ),
    ]
