# Generated by Django 5.2 on 2025-05-07 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pin', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('MbrCountryCode', models.CharField(choices=[('+91', 'India'), ('+1', 'USA'), ('+44', 'UK')], default='+91', max_length=5)),
                ('MbrStatus', models.BooleanField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('card_purposes', models.JSONField(default=list)),
                ('mbrcardno', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('mbraddress', models.CharField(blank=True, max_length=255, null=True)),
                ('MbrPincode', models.CharField(blank=True, max_length=6, null=True)),
                ('MbrReferalId', models.CharField(blank=True, max_length=50, null=True)),
                ('MbrCreatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('MbrCreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('MbrUpdatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('MbrUpdatedAt', models.DateTimeField(auto_now=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_member_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_member_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
