# Generated by Django 5.2 on 2025-05-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='app_common.member')),
            ],
            options={
                'verbose_name': 'Member Auth Token',
                'verbose_name_plural': 'Member Auth Tokens',
                'db_table': 'member_auth_token',
            },
        ),
    ]
