# Generated by Django 5.2 on 2025-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
