# Generated by Django 5.2 on 2025-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='login_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
