# Generated by Django 5.2 on 2025-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_member_login_id_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='login_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
