# Generated by Django 5.2 on 2025-05-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberauthtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
