# Generated by Django 5.2 on 2025-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0009_alter_memberauthtoken_created_at'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempBusinessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pin', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('business_id', models.CharField(blank=True, editable=False, max_length=6, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pin', models.CharField(blank=True, max_length=128, null=True)),
                ('business_name', models.CharField(blank=True, max_length=55, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Food', 'Food'), ('Health', 'Health'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Education', 'Education')], max_length=100, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('business_country_code', models.CharField(choices=[('+91', 'India'), ('+1', 'USA'), ('+44', 'UK')], default='+91', max_length=6)),
                ('business_is_active', models.BooleanField(default=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('business_created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('business_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('business_updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('business_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('business_notes', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_business_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_business_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
