# Generated by Django 5.2 on 2025-05-09 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0010_tempbusinessuser_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_auth_token', to='app_common.business')),
            ],
            options={
                'verbose_name': 'Business Auth Token',
                'verbose_name_plural': 'Business Auth Tokens',
                'db_table': 'business_auth_token',
            },
        ),
    ]
