# Generated by Django 5.2 on 2025-05-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0013_userauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField(unique=True)),
                ('issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_cards', to='app_common.business', to_field='business_id')),
            ],
        ),
    ]
