# Generated by Django 5.2 on 2025-05-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0014_physicalcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondary_card_type', models.CharField(choices=[('physical', 'Physical Card'), ('prepaid', 'Prepaid Card')], default='physical', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_mappings', to='app_common.business', to_field='business_id')),
                ('primary_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_card_mappings', to='app_common.member', to_field='mbrcardno')),
                ('secondary_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_mappings', to='app_common.physicalcard', to_field='card_number', verbose_name='Secondary Card')),
            ],
            options={
                'verbose_name': 'Card Mapper',
                'verbose_name_plural': 'Card Mappers',
                'unique_together': {('business', 'primary_card', 'secondary_card')},
            },
        ),
    ]
