# Generated by Django 5.2 on 2025-05-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0015_cardmapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
