# Generated by Django 5.2 on 2025-06-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0016_alter_member_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesskyc',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='app_common.business', to_field='business_id', verbose_name='Business'),
        ),
    ]
