# Generated by Django 5.2 on 2025-06-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0017_alter_businesskyc_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
