# Generated by Django 5.2 on 2025-06-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0019_user_is_jobmitra'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_institute',
            field=models.BooleanField(default=False),
        ),
    ]
