# Generated by Django 5.2 on 2025-06-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0020_business_is_business_business_is_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbusinessuser',
            name='is_institute',
            field=models.BooleanField(default=False),
        ),
    ]
