# Generated by Django 5.2 on 2025-06-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0021_tempbusinessuser_is_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='MbrPincode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mbraddress',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.JSONField(default=dict),
        ),
    ]
