# Generated by Django 5.2 on 2025-06-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0024_governmentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentuser',
            name='is_government',
            field=models.BooleanField(default=True),
        ),
    ]
