# Generated by Django 5.2 on 2025-07-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0026_governmentauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
