# Generated by Django 5.2 on 2025-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0027_business_business_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmapper',
            name='secondary_card',
            field=models.BigIntegerField(verbose_name='Secondary Card'),
        ),
        migrations.AlterField(
            model_name='cardmapper',
            name='secondary_card_type',
            field=models.CharField(choices=[('physical', 'Physical Card'), ('prepaid', 'Prepaid Card'), ('digital', 'Digital Card')], default='physical', max_length=20),
        ),
    ]
