# Generated by Django 5.2 on 2025-07-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0028_alter_cardmapper_secondary_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardmapper',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cardmapper',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cardmapper',
            name='business',
        ),
    ]
