# Generated by Django 5.2 on 2025-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0029_alter_cardmapper_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmapper',
            name='business_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
