# Generated by Django 5.2 on 2025-08-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0030_cardmapper_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Retail', 'Retail'), ('Food', 'Food'), ('Health', 'Health'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Education', 'Education'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
