# Generated by Django 5.2 on 2025-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0031_alter_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
