# Generated by Django 5.2 on 2025-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0032_alter_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='MbrStatus',
            field=models.BooleanField(default=True),
        ),
    ]
