# Generated by Django 5.2 on 2025-08-06 10:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_common', '0030_cardmapper_business_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('member', 'Member'), ('institute', 'Institute'), ('business', 'Business')], max_length=20, verbose_name='Lead Type')),
                ('status', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('neutral', 'Neutral')], max_length=10)),
                ('comments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_followups', to='app_common.business', to_field='business_id', verbose_name='Business ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_followups', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_followups', to='app_common.member', to_field='mbrcardno', verbose_name='Member Card Number')),
            ],
        ),
    ]
